const investmentNavigation=[
{title:'市盈率',en:'P/E Ratio',number:'15 倍',official:'股價除以每股盈利，用來觀察市場願意為公司每一元盈利付出多少。',metaphor:'像買一間茶餐廳：你不只看餐廳售價，也會看它一年能賺多少錢。',meaning:'15 倍代表投資者以目前盈利計算，理論上約需 15 年收回投入；不代表實際回本時間。',chart:'bar'},
{title:'市賬率',en:'P/B Ratio',number:'1.2 倍',official:'股價除以每股賬面值，用來比較市場價格和公司帳面資產。',metaphor:'像買樓時比較叫價和物業估值；叫價低不一定代表物業沒有問題。',meaning:'1.2 倍代表市場估值約為帳面資產的 1.2 倍，仍要了解資產質素。',chart:'line'},
{title:'貝塔系數',en:'Beta',number:'β ＝ 1.3',official:'衡量股票相對大市的歷史波動程度。',metaphor:'大市是一條普通巴士，Beta 1.3 的股票像避震較鬆的車，轉彎時搖晃更明顯。',meaning:'Beta 1.3 可理解為大市變動 1% 時，股票歷史上平均變動約 1.3%；不是保證。',chart:'wave'},
{title:'股息率',en:'Dividend Yield',number:'4.2%',official:'年度股息除以股價，用來估算持有股票的現金回報比例。',metaphor:'像把錢放進收租單位，股息就是定期收到的租金。',meaning:'4.2% 表示按目前股價計，年度股息約相當於投入金額的 4.2%；股息可能調整。',chart:'ring'},
{title:'市值',en:'Market Capitalisation',number:'$500 億',official:'股價乘以已發行股份數目，代表市場給公司的總估值。',metaphor:'像把一間公司的所有股份放上拍賣場，市值就是市場目前願意付出的總價。',meaning:'$500 億是規模估算，不代表公司銀行戶口真的有 $500 億現金。',chart:'bar'},
{title:'每手股數',en:'Lot Size',number:'1 手＝500 股',official:'交易所或券商規定的一手股票包含多少股。',metaphor:'像超市只按一箱出售，不能只買一罐；每手股數決定最低買入數量。',meaning:'500 股乘以股價，再加交易費，就是大約最低入場金額。',chart:'dots'},
{title:'分散投資',en:'Diversification',number:'60 / 30 / 10',official:'把資金分配到不同資產、地區或行業，以降低單一風險。',metaphor:'不要把所有雞蛋放在同一個籃子；一個籃子跌倒，不至於全部打破。',meaning:'60/30/10 是一個配置例子，不是標準答案；比例應配合目標和承受力。',chart:'mix'},
{title:'槓桿',en:'Leverage',number:'2 倍',official:'用借入資金放大投資部位，收益和損失都會被放大。',metaphor:'用 $1 加借來的 $1 買 $2 貨物，貨物跌價時自己的本金會更快減少。',meaning:'2 倍槓桿下，資產跌 10% 對本金的影響可能接近 20%，還未計利息和費用。',chart:'leverage'}
];
function navChart(type){const a='<path d="M10 132H290M10 132V12" stroke="#cbd5e1"/>';if(type==='bar')return`${a}<rect x="42" y="78" width="35" height="54" rx="5" fill="#9cc7ed"/><rect x="102" y="57" width="35" height="75" rx="5" fill="#73b6a0"/><rect x="162" y="39" width="35" height="93" rx="5" fill="#f1bd65"/><rect x="222" y="22" width="35" height="110" rx="5" fill="#3976c9"/>`;if(type==='ring')return`<circle cx="150" cy="75" r="50" fill="none" stroke="#e5eaf1" stroke-width="18"/><path d="M150 25A50 50 0 0 1 191 103" fill="none" stroke="#73b6a0" stroke-width="18"/><text x="126" y="82" fill="#24344d" font-size="20" font-weight="700">4.2%</text>`;if(type==='dots')return`${a}<g fill="#f1bd65" stroke="#d89b2c"><circle cx="70" cy="85" r="25"/><circle cx="130" cy="85" r="25"/><circle cx="190" cy="85" r="25"/><circle cx="250" cy="85" r="25"/></g><text x="213" y="35" fill="#718096" font-size="11">1 手</text>`;if(type==='mix')return`${a}<rect x="45" y="57" width="44" height="75" rx="5" fill="#3976c9"/><rect x="112" y="73" width="44" height="59" rx="5" fill="#73b6a0"/><rect x="179" y="101" width="44" height="31" rx="5" fill="#f1bd65"/><text x="48" y="48" fill="#3976c9" font-size="11">60%</text><text x="114" y="64" fill="#73b6a0" font-size="11">30%</text><text x="181" y="92" fill="#d89b2c" font-size="11">10%</text>`;if(type==='leverage')return`${a}<path d="M25 112L150 25L275 112" fill="none" stroke="#3976c9" stroke-width="5"/><path d="M25 120L150 78L275 120" fill="none" stroke="#e88472" stroke-width="5"/><text x="157" y="21" fill="#3976c9" font-size="11">資產 2x</text>`;if(type==='wave')return`${a}<path d="M15 108C43 80 63 112 90 78S138 45 165 76S210 72 236 42S268 60 290 27" fill="none" stroke="#3976c9" stroke-width="4"/>`;return`${a}<path d="M15 105L65 83L115 94L165 57L215 71L285 30" fill="none" stroke="#e88472" stroke-width="4"/>`}
function openTerm(item,group){document.getElementById('modal-badge').textContent=group;document.getElementById('modal-title').textContent=`${item.title}｜${item.en}`;document.getElementById('modal-official').textContent=item.official;document.getElementById('modal-metaphor').textContent=item.metaphor;document.getElementById('modal-meaning').textContent=item.meaning;const modal=document.getElementById('term-modal');modal.classList.add('is-open');modal.setAttribute('aria-hidden','false')}
function renderNavigation(){document.getElementById('navigation-container').innerHTML=investmentNavigation.map((item,index)=>`<button class="term-card term-card-button" type="button" data-nav-index="${index}"><div class="term-topline"><span class="term-number">${item.number}</span><span class="term-emoji">🧭</span></div><h3>${item.title}<small>${item.en}</small></h3><p>點擊查看三段解說及數值圖解。</p><figure><svg viewBox="0 0 300 150" role="img" aria-label="${item.title}數字圖表">${navChart(item.chart)}</svg></figure><div class="term-tip"><strong>🐱</strong><span>按此打開官方意思、生活比喻及數值背後含義</span></div></button>`).join('');document.querySelectorAll('[data-nav-index]').forEach(btn=>btn.addEventListener('click',()=>openTerm(investmentNavigation[btn.dataset.navIndex],'投資導航')))}
document.addEventListener('DOMContentLoaded',()=>{renderNavigation();const modal=document.getElementById('term-modal');document.querySelector('.modal-close').addEventListener('click',()=>{modal.classList.remove('is-open');modal.setAttribute('aria-hidden','true')});modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('is-open')})});
