const calculatorData={
freedom:{icon:'🌱',tag:'目標規劃',title:'財務自由計算器',desc:'由每月生活費與投資步伐，估算達到目標所需時間。',style:'green',official:'財務自由通常指被動收入或投資資產，足以長期覆蓋你的基本生活開支。',metaphor:'把每月開支想成水桶漏水；你的投資資產就是水庫，水庫夠大，便不用每天追著收入跑。',meaning:'結果是估算年數而不是保證日期。回報率、通脹、支出和中途提款都會改變答案。',fields:[['expense','每月生活費',25000],['assets','現有投資資產',300000],['monthly','每月投入',10000],['rate','預期年回報率',5]],calc(v){let target=v.expense*12/(v.rate/100||.0001),c=v.assets,y=0;while(c<target&&y<100){c=c*(1+v.rate/100)+v.monthly*12;y++}return[`${y>=100?'超過 100 年':y+' 年'}`,`目標資產約 ${money(target)}；假設年回報 ${v.rate}%`]}},
compound:{icon:'🪴',tag:'長線增值',title:'複利計算器',desc:'比較本金、每月投入、年回報與時間如何共同累積。',style:'blue',official:'複利是把已產生的利息或回報重新投入，讓下一期也可以產生回報。',metaphor:'第一年像種一棵小樹；後來樹上的果實也變成種子，時間越長，果園長得越快。',meaning:'終值包括本金和累積回報；年回報率只是模型假設，實際市場回報不會每年相同。',fields:[['principal','起始本金',100000],['monthly','每月投入',5000],['rate','預期年回報率',6],['years','投資年期',20]],calc(v){let r=v.rate/100/12,n=v.years*12,total=r? v.principal*Math.pow(1+r,n)+v.monthly*((Math.pow(1+r,n)-1)/r):v.principal+v.monthly*n;return[money(total),`投入本金合共 ${money(v.principal+v.monthly*n)}；累積回報約 ${money(total-v.principal-v.monthly*n)}`]}},
margin:{icon:'⚖️',tag:'風險管理',title:'IBKR 槓桿風險計算機',desc:'把本金、借款和股價跌幅放在一起，看清槓桿後的損益。',style:'red',official:'槓桿是用借入資金放大投資部位；保證金要求是券商維持帳戶安全的最低資產水平。',metaphor:'你用 $1 搭配借來的 $1 買 $2 貨物；貨物跌價時，自己的 $1 會更快被消耗。',meaning:'跌後權益是股價下跌後剩下的本金；若低於維持保證金，可能收到追繳或被強制平倉。',fields:[['equity','本金／帳戶權益',100000],['borrowed','借款金額',100000],['drop','假設股價跌幅',20],['maintenance','維持保證金要求',25]],calc(v){let pos=v.equity+v.borrowed,after=v.equity-pos*v.drop/100,ratio=pos?after/pos*100:0;return[ratio.toFixed(1)+'%',`跌後權益 ${money(after)}；維持要求 ${v.maintenance}%；${ratio<v.maintenance?'風險：低於維持要求':'暫時高於維持要求'}`]}},
assets:{icon:'🧭',tag:'資產整理',title:'資產監控工具',desc:'輸入不同資產類別，快速看見總額與配置比例。',style:'purple',official:'資產配置是把股票、債券、現金、強積金等資產按比例分布，以配合目標和風險承受力。',metaphor:'你的投資像一支足球隊；不能只靠一名前鋒，現金和債券也有守門和穩定作用。',meaning:'百分比是目前組合的快照，不是應該持有的標準答案；重點是定期檢視是否偏離計劃。',fields:[['stocks','股票／基金',300000],['bonds','債券',100000],['cash','現金／定存',100000],['mpf','強積金',200000],['other','其他資產',50000]],calc(v){let t=v.stocks+v.bonds+v.cash+v.mpf+v.other||1;return[money(t),`股票 ${(v.stocks/t*100).toFixed(1)}%｜債券 ${(v.bonds/t*100).toFixed(1)}%｜現金 ${(v.cash/t*100).toFixed(1)}%｜強積金 ${(v.mpf/t*100).toFixed(1)}%`]}},
bond:{icon:'🏦',tag:'固定收益',title:'債券收益計算機',desc:'以票面息率、買入價和持有期估算現金收益。',style:'gold',official:'債券收益來自票面利息和買賣價差；買入價低於面值時，持有至到期還可能有資本增值。',metaphor:'你借錢給一家公司，對方定期付茶錢；到期時再把原本借出的錢還給你。',meaning:'票面息率按面值計，現時收益率按你的買入價計；兩者不同，不能混用。',fields:[['face','債券面值',100000],['price','買入價',98000],['coupon','票面年息率',4],['years','持有年期',3]],calc(v){let coupon=v.face*v.coupon/100,total=coupon*v.years+v.face-v.price,annual=total/(v.price*v.years||1)*100;return[annual.toFixed(2)+'%',`估算總收益 ${money(total)}；每年票息 ${money(coupon)}；未計稅項及交易費`]}},
rule72:{icon:'🔁',tag:'投資入門',title:'72 法則翻倍體驗館',desc:'用簡單心算估計資產翻倍所需時間。',style:'orange',official:'72 法則以 72 除以年回報率，估算一筆資產翻倍所需年數。',metaphor:'像問貓貓要多久才可以把一碗糧變成兩碗；回報越高，等待時間越短，但風險通常也越高。',meaning:'這是近似值，沒有計入稅費、通脹及實際回報波動。',fields:[['rate','假設年回報率',6],['principal','目前本金',100000]],calc(v){let y=72/(v.rate||.0001);return['約 '+y.toFixed(1)+' 年',`${money(v.principal)} 翻倍約為 ${money(v.principal*2)}；這是近似值`]}},
carry:{icon:'🌏',tag:'跨市場',title:'港美利差交易計算機',desc:'比較港元與美元利率差，並扣除匯兌成本後的理論結果。',style:'teal',official:'利差交易是借入低息貨幣、持有較高息貨幣，賺取利率差；同時承受匯率和資金成本風險。',metaphor:'像在兩間銀行之間搬水：一邊借水較便宜，另一邊存水利息較高，但搬運途中匯率可能變。',meaning:'淨利差只是利率模型，不代表無風險；匯率變動 1% 已可能抵銷小幅息差。',fields:[['amount','本金（港元）',100000],['hkd','港元年利率',3.5],['usd','美元年利率',5],['fx','預計匯率／交易成本',.5]],calc(v){let net=v.usd-v.hkd-v.fx;return[net.toFixed(2)+'%',`一年理論淨收益 ${money(v.amount*net/100)}；已扣 ${v.fx}% 成本`]}},
saving:{icon:'🎯',tag:'儲蓄目標',title:'儲蓄計劃反推計算機',desc:'設定目標金額與期限，反推每月需要儲蓄多少。',style:'pink',official:'反推儲蓄是把目標金額、已有本金、時間和假設回報倒過來計算每月所需投入。',metaphor:'先決定目的地，再看每月要搭幾多站車；目標越近，每月車票通常越貴。',meaning:'結果是平均每月投入額；收入不穩定時，可當作最低基線，並保留應急現金。',fields:[['target','目標金額',300000],['current','現有儲蓄',50000],['months','剩餘月數',36],['rate','預期年回報率',2]],calc(v){let r=v.rate/100/12,n=v.months,need=r?(v.target-v.current*Math.pow(1+r,n))*r/(Math.pow(1+r,n)-1):(v.target-v.current)/(n||1);return[money(Math.max(0,need))+'/月',`${v.months} 個月後目標 ${money(v.target)}；假設回報 ${v.rate}%`]}}
};
function money(n){return new Intl.NumberFormat('zh-HK',{style:'currency',currency:'HKD',maximumFractionDigits:0}).format(Math.round(n||0))}function field(f){return`<label>${f[1]}<input data-field="${f[0]}" type="number" min="0" step="any" value="${f[2]}"></label>`}function render(){const key=document.body.dataset.toolPage,d=calculatorData[key];document.title=d.title+'｜貓貓投資學堂';document.getElementById('tool-root').innerHTML=`<section class="tool-panel ${d.style}"><div class="panel-heading"><div><span class="tool-tag">${d.tag}</span><h1>${d.icon} ${d.title}</h1><p>${d.desc}</p></div><a class="close-tool" href="tools.html">← 返回工具總覽</a></div><div class="tool-layout"><form class="tool-form"><h3>輸入資料</h3><div class="field-grid">${d.fields.map(field).join('')}</div><button class="btn" type="submit">立即計算 <span>→</span></button></form><div class="tool-result"><span>估算結果</span><strong id="result-main">—</strong><p id="result-sub">輸入資料後即時更新</p></div></div><div class="meaning-grid"><article><b>官方意思</b><p>${d.official}</p></article><article><b>生活比喻</b><p>${d.metaphor}</p></article><article><b>數值背後含義</b><p>${d.meaning}</p></article></div></section>`;const form=document.querySelector('form'),run=()=>{const v={};form.querySelectorAll('input').forEach(i=>v[i.dataset.field]=Number(i.value)||0);const r=d.calc(v);document.getElementById('result-main').textContent=r[0];document.getElementById('result-sub').textContent=r[1]};form.addEventListener('submit',e=>{e.preventDefault();run()});form.querySelectorAll('input').forEach(i=>i.addEventListener('input',run));run()}document.addEventListener('DOMContentLoaded',render);
